# Generated by Django 6.0.6 on 2026-07-12 06:46

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_singer_created_at_singer_updated_at_song_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='singer',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='music.tag'),
        ),
    ]
